apiVersion: v1
kind: Secret

metadata:
  name: {{ include "business-app.secretName" . }}
  labels:
    {{- include "business-app.commonLabels" . | nindent 4 }}

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.mysqlRootPassword | quote }}

  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.datasourceUsername | quote }}

  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.datasourcePassword | quote }}